제어문이나 comprehension을 이용한 문제풀이


[문제1]  
리스트에 저장된 문자열 중에서 길이가 5인 것들만 리스트 형태로 출력하도록 구현하세요.  

a= ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']  

[출력결과]     
['alpha', 'bravo', 'delta', 'hotel', 'india']

In [84]:
a = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']

result = [word for word in a if len(word) == 5]

print(result)

['alpha', 'bravo', 'delta', 'hotel', 'india']


[문제2]    
가로 크기를 저장한 리스트를 활용해서 가로 크기가 불규칙한  리스트를 생성하도록 프로그램을 구현하세요.

a = [3, 1,3, 2, 5]  


[출력결과]  
[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


In [79]:
a = [3, 1, 3, 2, 5]

result = [[0] * num for num in a]

print(result)

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


[문제3]    
포트폴리오의 총 비용을 계산하는 프로그램을 구현하세요.   

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]     

[출력결과]  
44671.15

In [81]:
portfolio = [
    {'name':'AA', 'shares':100, 'price':32.20},
    {'name':'IBM', 'shares':50, 'price':91.10},
    {'name':'CAT', 'shares':150, 'price':83.44},
    {'name':'MSFT', 'shares':200, 'price':51.23},
    {'name':'GE', 'shares':95, 'price':40.37},
    {'name':'MSFT', 'shares':50, 'price':65.10},
    {'name':'IBM', 'shares':100, 'price':70.44}
]

# portfolioShares = [shares['shares'] for shares in portfolio]
# portfolioPrice = [price['price'] for price in portfolio]

# total = [share * price for share, price in zip(portfolioShares, portfolioPrice)]
# cost = sum(total)

cost = sum(i['shares'] * i['price'] for i in portfolio)

print(cost)


44671.15


[문제4]  
포트폴리오에서 100주 이상 보유한 종목의 리스트를 출력하는 프로그램을 구현하세요.    
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]


[출력결과]    
[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]


In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

stocks = [i for i in portfolio if i['shares'] >= 100]

print(stocks)

[{'name': 'AA', 'shares': 100, 'price': 32.2}, {'name': 'CAT', 'shares': 150, 'price': 83.44}, {'name': 'MSFT', 'shares': 200, 'price': 51.23}, {'name': 'IBM', 'shares': 100, 'price': 70.44}]


[문제5]

보유한 MSFT와 IBM주식 전체 리스트를 출력하는 프로그램을 구현하세요.  

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  

[출력결과]   
[{'name': 'IBM', 'price': 91.1, 'shares': 50},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200},
 {'name': 'MSFT', 'price': 65.1, 'shares': 50},
 {'name': 'IBM', 'price': 70.44, 'shares': 100}]  



In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

# result = [item for item in portfolio if 'MSFT' in item['name'] or 'IBM' in item['name']]
result = [item for item in portfolio if item['name'] in {'MSFT', 'IBM'}]

print(result)

[{'name': 'IBM', 'shares': 50, 'price': 91.1}, {'name': 'MSFT', 'shares': 200, 'price': 51.23}, {'name': 'MSFT', 'shares': 50, 'price': 65.1}, {'name': 'IBM', 'shares': 100, 'price': 70.44}]


[문제6]
보유 종목 중 가격이 10,000달러가 넘는 것의 리스트를 구현하는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]    
[{'name': 'CAT', 'price': 83.44, 'shares': 150},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200}]

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

# shares*price > 10,000
result = [item for item in portfolio if item['shares'] * item['price'] > 10000]

print(result)

[{'name': 'CAT', 'shares': 150, 'price': 83.44}, {'name': 'MSFT', 'shares': 200, 'price': 51.23}]


[문제7]   
portfolio에서 얻은 name과 shares를 가지고 튜플의 리스트 (name, shares)를 만드는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]   
[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]



In [85]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

# name = [i['name'] for i in portfolio]
# shares = [i['shares'] for i in portfolio]

# result = [(n, s) for n, s in zip(name, shares)]

result = [(i['name'], i['shares']) for i in portfolio]

print(result)

[('AA', 100), ('IBM', 50), ('CAT', 150), ('MSFT', 200), ('GE', 95), ('MSFT', 50), ('IBM', 100)]


[문제8]  

리스트에서 int만 추출하는 프로그램을 구현하세요.  
oldlist = [1, 2, 'A', False, 3]

[출력결과]   
[1, 4, 9]  


In [ ]:
oldlist = [1, 2, 'A', False, 3]

result = [i for i in oldlist if type(i) == int]

print(result)

[1, 2, 3]


[문제9]   
1부터 10까지의 홀수, 짝수로 출력하는 프로그램을 구현하세요.

[출력결과]   
{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}


In [62]:
result = {}

# for i in range(1, 11):
#     if i % 2 == 0:
#         result[i] = '짝수'
#     else:
#         result[i] = '홀수'

result = {i: ('짝수' if i % 2 == 0 else '홀수') for i in range(1, 11)}

print(result)

{1: '홀수', 2: '짝수', 3: '홀수', 4: '짝수', 5: '홀수', 6: '짝수', 7: '홀수', 8: '짝수', 9: '홀수', 10: '짝수'}


 [문제10]  
 if~else문을 이용해서 년도에 해당하는 띠를 구하는 프로그램을 구현하시오.  
 단, 년도은 input()으로 입력받음.

   1. 12가지 띠  
      원숭이, 닭, 개, 돼지, 쥐, 소, 호랑이, 토끼, 용, 뱀, 말, 양  
   
   2. 띠구하는 공식  
     year%12의 결과가  
     0이면 "원숭이", 1이면 "닭"  2이면 "개",    3이면 "돼지",  
     4이면 "쥐",    5이면 "소", 6이면 "호랑이", 7이면 "토끼",  
     8이면 "용",    9이면 "뱀", 10이면 "말",   11이면 "양"  
     
   3. 출력결과  
     2012년도의 태생은  용띠입니다.  

In [71]:
year = int(input('몇 년생이신가요?'))
sign = ['원숭이', '닭', '개', '돼지', '쥐', '소', '호랑이', '토끼', '용', '뱀', '말', '양']

result = sign[year % 12]

print(f'{year}년도의 태생은 {result}띠입니다.')

2012년도의 태생은 용띠입니다.


[문제11]
list comprehension을 이용해서 1부터 10까지 합계 구하기

In [75]:
result = sum(i for i in range(1, 11))

print(result)

55


[문제12]
A 학급에 총 10명의 학생이 있다. 이 학생들의 중간고사 점수는 다음과 같다.

[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

list comprehension을 사용하여 A 학급의 평균 점수를 구해 보자.

In [86]:
scores = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

total = sum(s for s in scores)
avg = total / len(scores)

print(avg)

79.0


[문제13]
======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 1
메뉴명: 짜짜
가격: 3000
신규 메뉴 짜짜(이)가 등록되었습니다.
{'짜짜': '3000'}

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 2

==========메뉴판==========
짜짜 : 3000원
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기
> 3

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 3
프로그램을 종료합니다.

In [ ]:
foods = {}

while True:
    print("======음식점 메뉴 관리 프로그램======")
    print("1. 신규 메뉴 등록")
    print("2. 메뉴판 전체 보기")
    print("3. 프로그램 종료")

    try:
        num = int(input("> "))
    except ValueError:
        print("숫자를 입력해주세요.")
        continue
    
    
    if num == 1:
        # 1. 메뉴명을 입력받아 해당메뉴가 사전에 키로 존재한다면
        #    "이미 등록된 메뉴입니다"를 출력하세요
        # 2. 사전에 존재하지 않는 메뉴(key)라면 가격을 입력받아
        #    key:value쌍으로 맵핑하여 사전에 저장하세요.
        f_name = input("메뉴명: ")
        
        if f_name not in foods:
            price = int(input("가격: "))
            foods[f_name] = price
            print(f"신규 메뉴 {f_name}(이)가 등록되었습니다.")
        else:
            print("이미 등록된 메뉴입니다.")
        
        print(foods)

    elif num == 2:
        # 1. 모든 키를 뽑아내서 리스트로 만드세요.
        # 2. 해당 리스트를 반복문으로 순회하여 메뉴와 가격을 출력하세요.
        #  ex) 출력 예시: "김치찌개 : 7000원"
        if not foods:
            print("등록된 메뉴가 없습니다.")
            continue

        menulist = foods.keys()

        print("==========메뉴판==========")
        
        for menu in menulist:
            print(f"{menu}: {foods[menu]}원")
        print("----------------------------------")
        print("1. 수정 | 2. 삭제 | 3. 나가기")

        try:
            select = int(input("> "))
        except ValueError:
            print("숫자를 입력해주세요.")
            continue

        if select == 1:
            name = input("가격을 변경할 메뉴의 이름을 입력하세요: ")

            # 해당 메뉴가 존재하는지 확인
            if name in foods:
                newPrice = int(input("변경할 가격 입력: "))
                # 해당 메뉴의 가격을 newPrice로 변경
                foods[name] = newPrice
                print(f"{name}의 가격이 {newPrice}원으로 변경되었습니다.")
            else:
                print(f"{name}(은)는 등록된 메뉴가 아닙니다.")
        elif select == 2:
            name = input("삭제할 메뉴의 이름을 입력하세요: ")

            # 해당 메뉴가 존재하는지 확인
            if name in foods:
                del(foods[name])
                print(f"{name}(이)가 삭제되었습니다.")
            else:
                print(f"{name}(은)는 등록된 메뉴가 아닙니다.")
        # elif select == 3:
        #     continue
        else:
            print("잘못된 번호입니다. 다시 입력해주세요.")
    
    elif num == 3:
        print("프로그램을 종료합니다.")
        break

    else:
        print("잘못된 번호입니다. 다시 입력해주세요.")

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
잘못된 번호입니다.
======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
프로그램을 종료합니다.
